export default [
  {
    id: '1',
    categoryId: '1',
    name: 'Jacket purple',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 823,
    image: '/uploads/violet.jpg',
    image_2: '/uploads/violet_2.jpg',
    image_3: '/uploads/violet_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '2',
    categoryId: '1',
    name: 'Red T-shirt',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 953,
    image_2: '/uploads/red_2.jpg',
    image_3: '/uploads/red_3.jpg',
    image: '/uploads/red.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '3',
    categoryId: '4',
    name: 'Pink jacket',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 764,
    image: '/uploads/rose.jpg',
    image_2: '/uploads/rose_2.jpg',
    image_3: '/uploads/rose_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '4',
    categoryId: '5',
    name: 'Checkered dress',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 674,
    image: '/uploads/dress.jpg',
    image_2: '/uploads/dress_2.jpg',
    image_3: '/uploads/dress_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '5',
    categoryId: '3',
    name: 'Red jacket',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 975,
    image: '/uploads/red_jak.jpg',
    image_2: '/uploads/red_jak_2.jpg',
    image_3: '/uploads/red_jak_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '6',
    categoryId: '2',
    name: 'Green pullover',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 515,
    image: '/uploads/green_pul.jpg',
    image_2: '/uploads/green_pul_2.jpg',
    image_3: '/uploads/green_pul_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },


  {
    id: '7',
    categoryId: '1',
    name: 'Black jacket',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 823,
    image: '/uploads/black_jacket.jpg',
    image_2: '/uploads/black_jacket_2.jpg',
    image_3: '/uploads/black_jacket_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '8',
    categoryId: '1',
    name: 'Blue suit',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 953,
    image: '/uploads/blue_suit.jpg',
    image_2: '/uploads/blue_suit_2.jpg',
    image_3: '/uploads/blue_suit_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '9',
    categoryId: '4',
    name: 'Brown pullover',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 764,
    image: '/uploads/brown_pull.jpg',
    image_2: '/uploads/brown_pull_2.jpg',
    image_3: '/uploads/brown_pull_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '10',
    categoryId: '5',
    name: 'Green dress',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 674,
    image: '/uploads/green_dress.jpg',
    image_2: '/uploads/green_dress_2.jpg',
    image_3: '/uploads/green_dress_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '11',
    categoryId: '3',
    name: 'Military jacket',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 975,
    image: '/uploads/military.jpg',
    image_2: '/uploads/military_2.jpg',
    image_3: '/uploads/military_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  },
  {
    id: '12',
    categoryId: '2',
    name: 'Red pullover',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 515,
    image: '/uploads/red_pullover.jpg',
    image_2: '/uploads/red_pullover_2.jpg',
    image_3: '/uploads/red_pullover_3.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: 'XL/L/M/S',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB'
  }
]
