export default [
  {
    id: '1',
    categoryId: '1',
    categoryItem: 'Jacket',
    name: 'Jacket purple',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (823).toFixed(2),
    discount: Math.abs(823 * 0.75).toFixed(2),
    image: '/uploads/violet.jpg', // преобразовать в массив [imgUrl, imgUrl]
    // images: [
    //   require('/uploads/violet1.jpg'),
    //   require('/uploads/violet1.jpg'),
    //   require('/uploads/violet1.jpg'),
    // ],
    image_2: '/uploads/violet_2.jpg',
    image_3: '/uploads/violet_3.jpg',
    size: 'XL/L/M/S',

  },
  {
    id: '2',
    categoryId: '4',
    categoryItem: 'T-shirt',
    name: 'Red T-shirt',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (953).toFixed(2),
    discount: Math.abs(953 * 0.85).toFixed(2),
    image_2: '/uploads/red_2.jpg',
    image_3: '/uploads/red_3.jpg',
    image: '/uploads/red.jpg',
    size: 'XL/L/M/S',

  },
  {
    id: '3',
    categoryId: '1',
    categoryItem: 'Jacket',
    name: 'Pink jacket',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (764).toFixed(2),
    discount: Math.abs(764 * 0.65).toFixed(2),
    image: '/uploads/rose.jpg',
    image_2: '/uploads/rose_2.jpg',
    image_3: '/uploads/rose_3.jpg',
    size: 'XL/L/M/S',
  },
  {
    id: '4',
    categoryId: '3',
    categoryItem: 'Dress',
    name: 'Checkered dress',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (674).toFixed(2),
    discount: Math.abs(674 * 0.85).toFixed(2),
    image: '/uploads/dress.jpg',
    image_2: '/uploads/dress_2.jpg',
    image_3: '/uploads/dress_3.jpg',
    size: 'XL/L/M/S',
  },
  {
    id: '5',
    categoryId: '1',
    categoryItem: 'Jacket',
    name: 'Red jacket',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (975).toFixed(2),
    discount: Math.abs(975 * 0.75).toFixed(2),
    image: '/uploads/red_jak.jpg',
    image_2: '/uploads/red_jak_2.jpg',
    image_3: '/uploads/red_jak_3.jpg',
    size: 'XL/L/M/S',
  },
  {
    id: '6',
    categoryId: '2',
    categoryItem: 'Pullover',
    name: 'Green pullover',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (515).toFixed(2),
    discount: Math.abs(515 * 0.85).toFixed(2),
    image: '/uploads/green_pul.jpg',
    image_2: '/uploads/green_pul_2.jpg',
    image_3: '/uploads/green_pul_3.jpg',
    size: 'XL/L/M/S',
  },


  {
    id: '7',
    categoryId: '1',
    categoryItem: 'Jacket',
    name: 'Black jacket',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (823).toFixed(2),
    discount: Math.abs(823 * 0.85).toFixed(2),
    image: '/uploads/black_jacket.jpg',
    image_2: '/uploads/black_jacket_2.jpg',
    image_3: '/uploads/black_jacket_3.jpg',
    size: 'XL/L/M/S',
  },
  {
    id: '8',
    categoryId: '5',
    categoryItem: 'Suit',
    name: 'Blue suit',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (953).toFixed(2),
    discount: Math.abs(953 * 0.85).toFixed(2),
    image: '/uploads/blue_suit.jpg',
    image_2: '/uploads/blue_suit_2.jpg',
    image_3: '/uploads/blue_suit_3.jpg',
    size: 'XL/L/M/S',
  },
  {
    id: '9',
    categoryId: '2',
    categoryItem: 'Pullover',
    name: 'Brown pullover',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (764).toFixed(2),
    discount: Math.abs(764 * 0.75).toFixed(2),
    image: '/uploads/brown_pull.jpg',
    image_2: '/uploads/brown_pull_2.jpg',
    image_3: '/uploads/brown_pull_3.jpg',
    size: 'XL/L/M/S',
  },
  {
    id: '10',
    categoryId: '3',
    categoryItem: 'Dress',
    name: 'Green dress',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (674).toFixed(2),
    discount: Math.abs(674 * 0.85).toFixed(2),
    image: '/uploads/green_dress.jpg',
    image_2: '/uploads/green_dress_2.jpg',
    image_3: '/uploads/green_dress_3.jpg',
    size: 'XL/L/M/S',
  },
  {
    id: '11',
    categoryId: '1',
    categoryItem: 'Jacket',
    name: 'Military jacket',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (975).toFixed(2),
    discount: Math.abs(953 * 0.85).toFixed(2),
    image: '/uploads/military.jpg',
    image_2: '/uploads/military_2.jpg',
    image_3: '/uploads/military_3.jpg',
    size: 'XL/L/M/S',
  },
  {
    id: '12',
    categoryId: '2',
    categoryItem: 'Pullover',
    name: 'Red pullover',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: (515).toFixed(2),
    discount: Math.abs(515 * 0.85).toFixed(2),
    image: '/uploads/red_pullover.jpg',
    image_2: '/uploads/red_pullover_2.jpg',
    image_3: '/uploads/red_pullover_3.jpg',
    size: 'XL/L/M/S',
  }
]
